- name: Load SOPS secrets
  hosts: localhost
  gather_facts: false
  vars:
    sops_file: "{{ lookup('env', 'HOME') }}/OpenCloud/Dots/server_infra.yaml"
  tasks:
    - name: Decrypt SOPS file
      no_log: true
      ansible.builtin.set_fact:
        sops_raw: "{{ lookup('community.sops.sops', sops_file, errors='ignore') | from_yaml }}"

    - name: Map SOPS secrets
      no_log: true
      ansible.builtin.set_fact:
        sops_data:
          mydefaults: "{{ sops_raw.mydefaults | default({}, true) }}"
          tailscale: "{{ sops_raw.tailscale | default({}, true) }}"
          proxy: "{{ sops_raw.proxy | default({}, true) }}"
          vaultwarden: "{{ sops_raw.vaultwarden | default({}, true) }}"
          s3_hetzner: "{{ sops_raw.s3_hetzner | default({}, true) }}"
          ntfy: "{{ sops_raw.ntfy | default({}, true) }}"
          opencloud: "{{ sops_raw.opencloud | default({}, true) }}"
          freshrss: "{{ sops_raw.freshrss | default({}, true) }}"
          immich: "{{ sops_raw.immich | default({}, true) }}"
          audiobookshelf: "{{ sops_raw.audiobookshelf | default({}, true) }}"
          actual_budget: "{{ sops_raw.actual_budget | default({}, true) }}"
          mealie: "{{ sops_raw.mealie | default({}, true) }}"

- name: System Defaults
  hosts: all
  become: true
  gather_facts: true
  vars:
    security_sudoers_passwordless:
      - "{{ ansible_user }}"
  roles:
    - role: geerlingguy.security
      tags: [defaults, security]
    - role: mydefaults
      tags: [defaults]
    - role: geerlingguy.docker
      tags: [defaults, docker]

- name: Tailscale
  hosts:
    - pivpn
    - homeeins-1
  become: true
  gather_facts: true
  tags: [tailscale]
  pre_tasks:
    - name: Ensure IP forwarding sysctl settings
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
      loop:
        - { name: "net.ipv4.ip_forward", value: "1" }
        - { name: "net.ipv6.conf.all.forwarding", value: "1" }
      notify: Reload sysctl

  roles:
    - role: artis3n.tailscale.machine
      vars:
        verbose: true
        tailscale_authkey: "{{ sops.tailscale.client_secret }}"
        tailscale_tags:
          - "server"
        tailscale_args: >-
          --advertise-exit-node
          --advertise-routes={{ ansible_facts.default_ipv4.network }}/{{ ansible_facts.default_ipv4.prefix }}
        tailscale_oauth_ephemeral: false
        tailscale_oauth_preauthorized: false

  handlers:
    - name: Reload sysctl
      ansible.builtin.command: sysctl -p
      changed_when: false

- name: Setup Traefik
  hosts: homeeins-1
  become: true
  tags: [traefik]
  roles:
    - traefik

- name: Setup vaultwarden
  hosts: homeeins-1
  become: true
  tags: [vaultwarden]
  roles:
    - vaultwarden

- name: Setup audiobookshelf
  hosts: homeeins-1
  become: true
  tags: [audiobookshelf]
  roles:
    - audiobookshelf

- name: Setup ntfy
  hosts: homeeins-1
  become: true
  tags: [ntfy]
  roles:
    - ntfy

- name: Setup OpenCloud
  hosts: homeeins-1
  become: true
  tags: [opencloud]
  roles:
    - opencloud

- name: Setup Actual
  hosts: homeeins-1
  become: true
  tags: [actual_budget]
  roles:
    - actual_budget

- name: Setup FreshRSS
  hosts: homeeins-1
  become: true
  tags: [freshrss]
  roles:
    - freshrss

- name: Setup Immich
  hosts: homeeins-1
  become: true
  tags: [immich]
  roles:
    - immich


- name: Setup Mealie
  hosts: homeeins-1
  become: true
  tags: [mealie]
  roles:
    - mealie

- name: Setup restic backups
  hosts: homeeins-1
  become: true
  tags: [restic_backup]
  roles:
    - restic_backup
