---
- ansible.builtin.import_playbook: playbooks/secrets.yaml
- ansible.builtin.import_playbook: playbooks/bootstrap.yaml
- ansible.builtin.import_playbook: playbooks/system.yaml
- ansible.builtin.import_playbook: playbooks/network.yaml
- ansible.builtin.import_playbook: playbooks/services.yaml
- ansible.builtin.import_playbook: playbooks/backups.yaml
- ansible.builtin.import_playbook: playbooks/hosts.yaml
