- name: Load SOPS secrets
  hosts: localhost
  gather_facts: false
  vars:
    sops_file: "{{ lookup('env', 'HOME') }}/Documents/Dots/server_infra.yaml"
  tasks:
    - name: Read SOPS secrets
      no_log: true
      vars:
        sops_raw: "{{ lookup('community.sops.sops', sops_file, errors='ignore') | from_yaml }}"
      ansible.builtin.set_fact:
        sops_data:
          mydefaults: "{{ sops_raw.mydefaults | default({}, true) }}"
          tailscale: "{{ sops_raw.tailscale | default({}, true) }}"
          proxy: "{{ sops_raw.proxy | default({}, true) }}"
          vaultwarden: "{{ sops_raw.vaultwarden | default({}, true) }}"

- name: System Defaults
  hosts: all
  become: true
  gather_facts: true
  vars:
    sops: "{{ hostvars['localhost'].sops_data }}"
    security_sudoers_passwordless:
      - "{{ ansible_facts.user_id }}"
    security_ssh_port: 6861
    security_ssh_password_authentication: "no"
    security_ssh_permit_root_login: "no"
    security_ssh_permit_empty_password: "no"
    security_autoupdate_enabled: true
    security_autoupdate_reboot: true
    security_autoupdate_reboot_time: "04:00"
    security_fail2ban_enabled: true
  roles:
    - geerlingguy.security
    - mydefaults
    - geerlingguy.docker

- name: PiVPN
  hosts: pivpn
  become: true
  gather_facts: true
  vars:
    sops: "{{ hostvars['localhost'].sops_data }}"
  pre_tasks:
    - name: Ensure IP forwarding sysctl settings
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
      loop:
        - { name: "net.ipv4.ip_forward", value: "1" }
        - { name: "net.ipv6.conf.all.forwarding", value: "1" }
      notify: Reload sysctl

  roles:
    - role: artis3n.tailscale.machine
      vars:
        verbose: true
        tailscale_authkey: "{{ sops.tailscale.client_secret }}"
        tailscale_tags:
          - "server"
        tailscale_args: >-
          --advertise-exit-node
          --advertise-routes={{ ansible_facts.default_ipv4.network }}/{{ ansible_facts.default_ipv4.prefix }}
        tailscale_oauth_ephemeral: false
        tailscale_oauth_preauthorized: false

  handlers:
    - name: Reload sysctl
      ansible.builtin.command: sysctl -p
      changed_when: false

- name: Setup Traefik
  hosts: pivpn
  become: true
  vars:
    sops: "{{ hostvars['localhost'].sops_data }}"
  roles:
    - traefik

- name: Setup vaultwarden
  hosts: pivpn
  become: true
  vars:
    sops: "{{ hostvars['localhost'].sops_data }}"
  roles:
    - vaultwarden
