- name: "SSH juggle Port"
  hosts: all
  gather_facts: false
  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yaml

- name: "Base"
  hosts: all
  become: true
  roles:
    - system
    - geerlingguy.security
    - geerlingguy.firewall

- name: "PiVPN"
  hosts: pivpn
  become: true
  pre_tasks:
    - name: IPv4-Forwarding aktivieren
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: true
        state: present
        reload: true

    - name: IPv6-Forwarding aktivieren
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: "1"
        sysctl_set: true
        state: present
        reload: true

  roles:
    - role: artis3n.tailscale.machine
      vars:
        verbose: true
        tailscale_authkey: "{{ lookup('community.general.passwordstore', 'infra/tailscale_oauth', subkey='client-secret') }}"
        tailscale_tags:
          - "server"
        tailscale_args: "--advertise-exit-node"
        tailscale_oauth_ephemeral: false
        tailscale_oauth_preauthorized: false

- name: "NAS & Docker"
  hosts: nas
  become: true
  roles:
    - geerlingguy.docker
    - portainer
