- name: Load SOPS secrets
  hosts: localhost
  gather_facts: false
  vars:
    sops_file: "{{ lookup('env', 'HOME') }}/OpenCloud/Dots/server_infra.yaml"
  tasks:
    - name: Read SOPS secrets
      no_log: true
      vars:
        sops_raw: "{{ lookup('community.sops.sops', sops_file, errors='ignore') | from_yaml }}"
      ansible.builtin.set_fact:
        sops_data:
          mydefaults: "{{ sops_raw.mydefaults | default({}, true) }}"
          ubuntu: "{{ sops_raw.ubuntu | default({}, true) }}"

- name: Build custom Ubuntu autoinstall ISO
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    sops: "{{ hostvars['localhost'].sops_data }}"
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - role: ansible-role-ubuntu_autoinstall
