---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start calendar sync timer
  ansible.builtin.systemd:
    name: vdirsyncer-clean-sync.timer
    enabled: true
    state: started

- name: Run calendar sync
  ansible.builtin.systemd:
    name: vdirsyncer-clean-sync.service
    state: started
