---
- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - vdirsyncer
    state: present

- name: Ensure vdirsyncer system user exists
  ansible.builtin.user:
    name: vdirsyncer
    system: true
    shell: /usr/sbin/nologin
    create_home: true
    home: /var/lib/vdirsyncer

- name: Ensure vdirsyncer config dir exists
  ansible.builtin.file:
    path: /var/lib/vdirsyncer/.vdirsyncer
    state: directory
    owner: vdirsyncer
    group: vdirsyncer
    mode: "0700"

- name: Ensure vdirsyncer clean dir exists
  ansible.builtin.file:
    path: /var/lib/vdirsyncer/localclean
    state: directory
    owner: vdirsyncer
    group: vdirsyncer
    mode: "0700"

- name: Ensure vdirsyncer clean collection dir exists
  ansible.builtin.file:
    path: /var/lib/vdirsyncer/localclean/cleaned
    state: directory
    owner: vdirsyncer
    group: vdirsyncer
    mode: "0700"

- name: Deploy vdirsyncer config
  no_log: true
  ansible.builtin.template:
    src: config.j2
    dest: /var/lib/vdirsyncer/.vdirsyncer/config
    owner: vdirsyncer
    group: vdirsyncer
    mode: "0600"
  notify:
    - Run attendee stripping sync

- name: Ensure env dir exists
  ansible.builtin.file:
    path: /etc/vdirsyncer
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Deploy vdirsyncer environment file
  no_log: true
  ansible.builtin.template:
    src: env.j2
    dest: /etc/vdirsyncer/env
    owner: root
    group: root
    mode: "0600"
  notify:
    - Run attendee stripping sync

- name: Deploy attendee stripping helper script
  ansible.builtin.template:
    src: strip_attendees.sh.j2
    dest: /usr/local/bin/strip_attendees.sh
    owner: root
    group: root
    mode: "0755"
  notify:
    - Run attendee stripping sync

- name: Deploy systemd service unit
  ansible.builtin.template:
    src: vdirsyncer-clean-sync.service.j2
    dest: /etc/systemd/system/vdirsyncer-clean-sync.service
    mode: "0644"
  notify:
    - Reload systemd daemon

- name: Deploy systemd timer unit
  ansible.builtin.template:
    src: vdirsyncer-clean-sync.timer.j2
    dest: /etc/systemd/system/vdirsyncer-clean-sync.timer
    mode: "0644"
  notify:
    - Reload systemd daemon
    - Enable and start attendee stripping timer
    - Run attendee stripping sync
