hostname: '{{ inventory_hostname }}'

timezone: Europe/Berlin

ntp_timezone: '{{ timezone }}'

locale: de_DE.UTF-8

keyboard_layout: de



docker_dir: /opt/docker/data

docker_compose_dir: /opt/docker/compose

docker_daemon_options:
  storage-driver: "overlay2"


security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"


security_sudoers_passwordless: ['{{ ansible_user }}']

security_autoupdate_reboot: true

security_autoupdate_reboot_time: '23:00'

security_fail2ban_enabled: true
