---
- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
    reboot_timeout: 300   # (= 5 minutes)
  when: reboot_required_file.stat.exists

- name: Install basic packages
  package:
    name:
      - neovim
      - curl
      - git
      - ssh
    state: latest

- name: Add some shortcuts to .bashrc
  blockinfile:
    path: /etc/bash.bashrc
    block: |
      # some more ls aliases
      alias l='ls -la'
      alias '..'='cd ..'

# - name: Set the hostname
#   hostname:
#     name: "{{ inventory_hostname }}"
# 
# - name: Replace the hostname entry with our own
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     insertafter: ^127\.0\.0\.1 *localhost
#     line: "127.0.0.1 {{ inventory_hostname }}"
#     owner: root
#     group: root
#     mode: '0644'
