---
- name: Set the name of a sudo group
  set_fact:
    sudo_group: sudo

- name: Ensure the necessary groupsexists
  group:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ ansible_user }}"
    - docker

- name: Create a login user
  user:
    name: "{{ ansible_user }}"
    password: "{{ lookup('community.general.passwordstore', user_passwordstore_entry) | password_hash('sha512') }}"
    groups:
      - "{{ sudo_group }}"
      - docker
      - users
    state: present
    append: true

- name: Chmod the user home directory
  file:
    path: "/home/{{ ansible_user }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

- name: Allow '{{ sudo_group }}' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%{{ sudo_group }}"
    line: "%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Set authorized keys taken from github
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "https://github.com/{{ github_name }}.keys"

- name: Clear gathered facts from all currently targeted hosts
  ansible.builtin.meta: reset_connection

- name: Entferne Default-User
  ansible.builtin.user:
    name: "{{ lookup('community.general.passwordstore', 'infra/initial_creds', subkey='user') }}"  
    state: absent     # sorgt dafür, dass der Benutzer gelöscht wird
    remove: yes       # löscht auch das Home-Verzeichnis und Mail-Spool
