---
- name: Make sure that the freshrss extensions folder exists
  ansible.builtin.file:
    path: "{{ docker_dir }}/freshrss/extensions/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: Download freshrss-youtube extension
  ansible.builtin.unarchive:
    src: https://github.com/kevinpapst/freshrss-youtube/archive/master.zip
    dest: "{{ docker_dir }}/freshrss/extensions/"
    remote_src: true

- name: Copy freshrss-youtube extension to destination dir
  ansible.builtin.copy:
    src: "{{ docker_dir }}/freshrss/extensions/freshrss-youtube-master/xExtension-YouTube"
    dest: "{{ docker_dir }}/freshrss/extensions/"
    remote_src: true

- name: Cleanup
  file:
    state: absent
    path: "{{ docker_dir }}/freshrss/extensions/freshrss-youtube-master"

- name: Download freshrss-readable extension
  ansible.builtin.unarchive:
    src: https://github.com/printfuck/xExtension-Readable/archive/refs/heads/master.zip
    dest: "{{ docker_dir }}/freshrss/extensions/"
    remote_src: true
